
DATA_ROOT_DIRECTORY = 'data/raw_submission'
TAR_DATA_ROOT_DIRECTORY = 'data'
TAR_FILE_NAME = 'raw_submission.tar.gz'

METHODOLOGY_KEYWORDS = ('sequence alignment',
                        'sequence-profile alignment',
                        'profile-profile alignment',
                        'phylogeny',
                        'sequence properties',
                        'physicochemical properties',
                        'predicted properties',
                        'protein interactions',
                        'gene expression',
                        'mass spectrometry',
                        'genetic interactions',
                        'protein structure',
                        'literature',
                        'genomic context',
                        'synteny',
                        'structure alignment',
                        'comparative model',
                        'predicted protein structure',
                        'de novo prediction',
                        'machine learning',
                        'genome environment',
                        'operon',
                        'ortholog',
                        'paralog',
                        'homolog',
                        'hidden Markov model',
                        'clinical data',
                        'genetic data',
                        'natural language processing',
                        'other functional information')
